# Generated by Django 4.1.7 on 2023-03-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_instruction_images_remove_instruction_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipevideo',
            old_name='image',
            new_name='video',
        ),
    ]
