# Generated by Django 4.1.7 on 2023-04-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
