# Generated by Django 4.1.7 on 2023-04-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(choices=[('tsp', 'Teaspoon'), ('tbs', 'Tablespoon'), ('cup', 'Cup'), ('oz', 'Ounce'), ('mg', 'Milligram'), ('g', 'Gram'), ('kg', 'Kilogram'), ('lbs', 'Pounds'), ('mL', 'Millilitre'), ('L', 'Litre'), ('', '')], max_length=10),
        ),
    ]
