# Generated by Django 4.1.7 on 2023-04-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredient_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='num_servings',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
